 WITH TRANSFERT AS (
SELECT 
    
   SUBSTR(LECR_REFERENCE_OPER,-12,12) MANDAT, B.*, TY.BT_TYPE_STATUS_LIB
FROM EXECUTION%ANNEE%.LGECRITURE L
, TRANSFERT.DETAILS_BT_EMIS DT, TRANSFERT.BT B
, TRANSFERT.BT_TYPE_STATUS TY
WHERE
/*ECRI_NUM = 128601
AND*/ LECR_REFERENCE_OPER LIKE 'CD|MD-%'
AND LECR_SENS  = 'C'
AND  L.LECR_NUM = DT.DET_BT_ENV_LECRNUM 
AND L.ENTITE = DT.BTE_ENVOYEUR
AND B.BT_ID = DT.DET_BT_ENV_ID
AND B.BT_STATUS = TY.BT_TYPE_STATUS_ID
)
 SELECT COUNT(*) over () FOUND_ROWS,
	   (SELECT PSTP_LIBELLE FROM EXECUTION%ANNEE%.POSTE_COMPTABLE_ORIGINAL@dblcca2 pc WHERE M.ASSIGNATAIRE=pc.PSTP_CODE) as ASSIGNATAIRE1,
	   (SELECT PSTP_LIBELLE FROM EXECUTION%ANNEE%.POSTE_COMPTABLE_ORIGINAL@dblcca2 pc WHERE M.MANDATAIRE=pc.PSTP_CODE) as MANDATAIRE1,
	   M.SOA,
	   BT_ENV_ANNUL_DATE,
	   BT_ENV_VALID_DATE,
	   BT_REC_DATE,
	   BT_REC_VALID_DATE,
	   BT_REC_VALID_DATE,
	   M.COMPTE,
	   M.MAND_VISA_TEF,
	   M.MAND_NUM_INFO    NUMERO_MANDAT,
	   T.NUMERO_TITRE     NUMERO_TITRE,
	   T.CODE_TIERS       CODE_TIERS,
	   T.TITULAIRE        TITULAIRE,
	   M.MAND_OBJET,
	   T.MONTANT          MONTANT,
	   CONCAT (TO_CHAR(ECRI_MT,'FM999G999G999G999D00' , 'NLS_NUMERIC_CHARACTERS = '', '' '), ' Ar') AS ECRI_MT11,
	   M.MAND_DATE_RECUP,
	   M.MAND_DATE_REEL_VISA,
	   NVL(BT_TYPE_STATUS_LIB,CASE WHEN NVL(MAND_REJET,0) = 1 THEN 'REJET'
            WHEN NVL(ECRI_VALID,0) = 1 THEN 'ADMIS EN DEPENSE'
            WHEN NVL(MAND_VISA_VALIDE,0) = 1 AND NVL(ECRI_VALID,0) = 0 THEN 'EN INSTANCE DE VISA COMPTA'
            ELSE 'INSTANCE DE PRISE EN CHARGE' END) STATUS,
	   CASE
		   WHEN NVL (e.ecri_valid, 0) = 1 AND BT_REF IS NULL
		   THEN
			   'EN INSTANCE DE TRANSFERT'
		   WHEN NVL (e.ecri_valid, 0) = 1 AND BT_REF IS NOT NULL
		   THEN
			   BT_REC_VALID_USER
		   WHEN     m.MAND_COMPTE_CREDIT IS NOT NULL
				AND NVL (m.mand_rejet, 0) = 0
		   THEN
			   'VISE'
		   WHEN     m.MAND_COMPTE_CREDIT IS NULL
				AND NVL (m.mand_rejet, 0) = 1
		   THEN
			   'REJETE (Motif:' || M.rejet_note || ')'
		   WHEN M.MAND_DATE_TRAIT IS NULL
		   THEN
			   'RECUPERE AU NIVEAU GUICHET UNIQUE'
		   WHEN NVL (m.mand_date_recup,
					 TO_DATE ('01/01/2019', 'DD/MM/RRRR')) =
				TO_DATE ('01/01/2019', 'DD/MM/RRRR')
		   THEN
			   'DOSSIER NON PARVENU AU TRESOR'
	   END                STATUT,
	   BT_REF             REFERENCE,
	   CASE
		   WHEN BT_STATUS = '0'
		   THEN
			   TRUNC (BT_ENV_EDIT_DATE)
		   WHEN BT_STATUS = '2'
		   THEN
			   TRUNC (BT_ENV_VALID_DATE)
		   WHEN BT_STATUS = '4'
		   THEN
			   TRUNC (BT_REC_DATE)
		   WHEN BT_STATUS = '5'
		   THEN
			   TRUNC (BT_REC_VALID_DATE)
		   WHEN NVL (e.ecri_valid, 0) = 1 AND BT_REF IS NULL
		   THEN
			   TRUNC (E.ECRI_DT_VALID)
		   WHEN     m.MAND_COMPTE_CREDIT IS NOT NULL
				AND NVL (m.mand_rejet, 0) = 0
		   THEN
			   TRUNC (M.MAND_DATE_VISA)
		   WHEN     m.MAND_COMPTE_CREDIT IS NULL
				AND NVL (m.mand_rejet, 0) = 1
		   THEN
			   TRUNC (M.MAND_DT_RJT)
		   WHEN M.MAND_DATE_TRAIT IS NULL
		   THEN
			   TRUNC (M.MAND_DATE_RECUP)
		   WHEN NVL (m.mand_date_recup,
					 TO_DATE ('01/01/2019', 'DD/MM/RRRR')) =
				TO_DATE ('01/01/2019', 'DD/MM/RRRR')
		   THEN
			   TRUNC (M.MAND_DATE_ORD)
	 END                DATE_SITUATION,
	 M.ASSIGNATAIRE,
	   M.MANDATAIRE,
	   '' OVPCPAYEUR
  FROM EXECUTION%ANNEE%.MANDAT@dblcca2  M,
	   EXECUTION%ANNEE%.TITRE_XXI@dblcca2   T,
	   EXECUTION%ANNEE%.ECRITURE@dblcca2 E,
       TRANSFERT T
 WHERE 1=1
	   AND M.COMPTE NOT IN ('6011','6131','6522','6521')
	   AND M.MAND_MODE_PAIE = 'OO'
	   AND M.ECRI_NUM = E.ECRI_NUM(+)
	   AND M.ID_MAND = T.ID_MAND(+)
	   AND M.MAND_NUM_INFO = T.MANDAT (+)  
	   
	   
	   
	   