select %PARAM%,SUM(MAND_MONTANT) as MONTANT,COUNT(t.ECRI_NUM) as NOMBRE,to_char(ECRI_DT_VALID, 'MM') as Mois,ECRI_EXERCICE 
 from EXECUTION%ANNEE%.ECRITURE t,EXECUTION%ANNEE%.MANDAT m WHERE t.ECRI_NUM = m.ECRI_NUM
 AND t.PROP_CODE <> 'ERR' 
 AND ECRI_EXERCICE = '%ANNEE%' AND ECRI_DT_VALID IS NOT NULL
 GROUP BY %PARAM%,to_char(ECRI_DT_VALID, 'MM'),ECRI_EXERCICE
 ORDER BY %PARAM%,to_char(ECRI_DT_VALID, 'MM') ASC