select %PARAM%,
(CASE 
	WHEN SUBSTR (m.soa, 1, 1) ='4' THEN 'COMMUNE'
	WHEN SUBSTR (m.soa, 1, 1) ='2' THEN 'REGION'
	WHEN SUBSTR (m.soa, 1, 1) ='9' THEN 'EPN'
	ELSE 'ETAT'
END) as PROP_CODE,
SUM(MAND_MONTANT) as MONTANT,COUNT(t.ECRI_NUM) as NOMBRE,ECRI_EXERCICE 
from EXECUTION'%ANNEE%'.ECRITURE t,EXECUTION'%ANNEE%'.MANDAT m WHERE t.ECRI_NUM = m.ECRI_NUM
AND t.PROP_CODE <> 'ERR' 
AND ECRI_EXERCICE = '%ANNEE%' AND ECRI_DT_VALID IS NOT NULL
AND SUBSTR (m.soa, 1, 1) IN ('9','0','4','2')
GROUP BY %PARAM%,ECRI_EXERCICE
ORDER BY %PARAM% ASC