SELECT count(STATUT) as NOMBRE,1 as MONTANT,STATUT,MOIS
from (SELECT M.ASSIGNATAIRE,
	   ECRI_VALID,
	   MAND_REJET,
	   MAND_VISA_VALIDE,
	   MAND_UTR_VISA,
	   E.ECRI_NUM,
	   M.ENTITE,
	   to_char(NVL(NVL(ECRI_DT_CECRITURE,MAND_DT_RJT),MAND_DATE_TRAIT), 'MM') as Mois,
	   PERI_CODE,
	   MAND_MODE_PAIE,
	   M.SOA,
	   MIN_ABREV,
	   M.EXERCICE,
	   CASE
		   WHEN NVL (MAND_REJET, 0) = 1
		   THEN
			   'REJET'
		   WHEN NVL (ECRI_VALID, 0) = 1
		   THEN
			   'ADMIS EN DEPENSE'
		   WHEN NVL (MAND_VISA_VALIDE, 0) = 1 AND NVL (ECRI_VALID, 0) = 0
		   THEN
			   'EN INSTANCE DE VISA COMPTA'
		   ELSE
			   'EN INSTANCE DE PRISE EN CHARGE'
	   END                 STATUT
  FROM EXECUTION%ANNEE%.MANDAT M, EXECUTION%ANNEE%.ECRITURE E, CATIA.V_VIREMENT V
  WHERE     M.ECRI_NUM = E.ECRI_NUM(+)
	   AND M.ENTITE = E.ENTITE(+)
	   AND M.MAND_NUM_INFO = V.MANDAT(+)
	   AND M.EXERCICE = v.exercice(+)
 ) norm  
WHERE 1=1  