select %PARAM%,SUM(MAND_MONTANT) as montant,COUNT(t.ECRI_NUM) as nombre,ECRI_EXERCICE 
from EXECUTION%ANNEE%.ECRITURE t,EXECUTION%ANNEE%.MANDAT m WHERE t.ECRI_NUM = m.ECRI_NUM
AND t.PROP_CODE <> 'ERR' 
AND ECRI_EXERCICE = '%ANNEE%' AND ECRI_DT_VALID IS NOT NULL
GROUP BY %PARAM%,ECRI_EXERCICE
ORDER BY %PARAM% ASC