SELECT     
M.EXERCICE,
M.SOA,
M.COMPTE,
M.MAND_VISA_TEF,
M.MAND_NUM_INFO    NUMERO_MANDAT,
T.NUMERO_TITRE     NUMERO_TITRE,
T.CODE_TIERS       CODE_TIERS,
T.TITULAIRE        TITULAIRE,
M.MAND_OBJET,
T.MONTANT          MONTANT,
M.MAND_DATE_RECUP,
M.MAND_DATE_REEL_VISA,
CASE
WHEN NVL (v.OVREF, 'OV') <> 'OV' AND V.NOTESTATUS = '5'
THEN
   'VIRE'
WHEN NVL (e.ecri_valid, 0) = 1 AND m.mand_mode_paie = 'VB'
THEN
   'EN INSTANCE DE VIREMENT'
WHEN     m.MAND_COMPTE_CREDIT IS NOT NULL
	AND NVL (m.mand_rejet, 0) = 0
THEN
   'VISE'
WHEN     m.MAND_COMPTE_CREDIT IS NULL
	AND NVL (m.mand_rejet, 0) = 1
THEN
   'REJETE'-- (Motif:' || M.rejet_note || ')'
WHEN M.MAND_DATE_TRAIT IS NULL
THEN
   'RECUPERE AU NIVEAU GUICHET UNIQUE'
WHEN NVL (m.mand_date_recup,
		 TO_DATE ('01/01/2019', 'DD/MM/RRRR')) =
	TO_DATE ('01/01/2019', 'DD/MM/RRRR')
THEN
   'DOSSIER NON PARVENU AU TRESOR'
END                STATUT,
V.OVREF            REFERENCE,
CASE
WHEN NVL (v.OVREF, 'OV') <> 'OV' AND V.NOTESTATUS = '5'
THEN
   TRUNC (V.OVDATEVALID)
WHEN NVL (e.ecri_valid, 0) = 1 AND m.mand_mode_paie = 'VB'
THEN
   TRUNC (E.ECRI_DT_VALID)
WHEN     m.MAND_COMPTE_CREDIT IS NOT NULL
	AND NVL (m.mand_rejet, 0) = 0
THEN
   TRUNC (M.MAND_DATE_VISA)
WHEN     m.MAND_COMPTE_CREDIT IS NULL
	AND NVL (m.mand_rejet, 0) = 1
THEN
   TRUNC (M.MAND_DT_RJT)
WHEN M.MAND_DATE_TRAIT IS NULL
THEN
   TRUNC (M.MAND_DATE_RECUP)
WHEN NVL (m.mand_date_recup,
		 TO_DATE ('01/01/2019', 'DD/MM/RRRR')) =
	TO_DATE ('01/01/2019', 'DD/MM/RRRR')
THEN
   TRUNC (M.MAND_DATE_ORD)
END                DATE_SITUATION,
M.ASSIGNATAIRE,
M.MANDATAIRE,
V.OVPCPAYEUR
FROM EXECUTION%ANNEE%.MANDAT@dblcca2                M,
TITRE_XXI                 T,
EXECUTION%ANNEE%.ECRITURE@dblcca2              E,
T_VIREMENT  V
WHERE 1=1
AND M.COMPTE NOT IN ('6011','6131','6522','6521')
--AND M.SOA = '00-17-0-620-00000'
AND M.ID_MAND = T.ID_MAND
AND M.ENTITE = T.ENTITE
AND M.ECRI_NUM = E.ECRI_NUM(+)
--AND M.MAND_NUM_INFO=v.infonumero (+)
AND T.NUMERO_TITRE = V.TITRENUMERO(+)
--AND V.NOTESTATUS(+) = '5'
AND M.MAND_MODE_PAIE = 'VB'
UNION
SELECT 
M.EXERCICE,
M.SOA,
M.COMPTE,
M.MAND_VISA_TEF,
M.MAND_NUM_INFO    NUMERO_MANDAT,
T.NUMERO_TITRE     NUMERO_TITRE,
T.CODE_TIERS       CODE_TIERS,
T.TITULAIRE        TITULAIRE,
M.MAND_OBJET,
T.MONTANT          MONTANT,
M.MAND_DATE_RECUP,
M.MAND_DATE_REEL_VISA,
CASE
WHEN NVL (e.ecri_valid, 0) = 1 AND BT_REF IS NULL
THEN
   'EN INSTANCE DE TRANSFERT'
WHEN NVL (e.ecri_valid, 0) = 1 AND BT_REF IS NOT NULL
THEN
   LIB_STATUS
WHEN     m.MAND_COMPTE_CREDIT IS NOT NULL
	AND NVL (m.mand_rejet, 0) = 0
THEN
   'VISE'
WHEN     m.MAND_COMPTE_CREDIT IS NULL
	AND NVL (m.mand_rejet, 0) = 1
THEN
   'REJETE (Motif:' || M.rejet_note || ')'
WHEN M.MAND_DATE_TRAIT IS NULL
THEN
   'RECUPERE AU NIVEAU GUICHET UNIQUE'
WHEN NVL (m.mand_date_recup,
		 TO_DATE ('01/01/2019', 'DD/MM/RRRR')) =
	TO_DATE ('01/01/2019', 'DD/MM/RRRR')
THEN
   'DOSSIER NON PARVENU AU TRESOR'
END                STATUT,
BT_REF             REFERENCE,
CASE
WHEN BT_STATUS = '0'
THEN
   TRUNC (BT_ENV_EDIT_DATE)
WHEN BT_STATUS = '2'
THEN
   TRUNC (BT_ENV_VALID_DATE)
WHEN BT_STATUS = '4'
THEN
   TRUNC (BT_REC_DATE)
WHEN BT_STATUS = '5'
THEN
   TRUNC (BT_REC_VALID_DATE)
WHEN NVL (e.ecri_valid, 0) = 1 AND BT_REF IS NULL
THEN
   TRUNC (E.ECRI_DT_VALID)
WHEN     m.MAND_COMPTE_CREDIT IS NOT NULL
	AND NVL (m.mand_rejet, 0) = 0
THEN
   TRUNC (M.MAND_DATE_VISA)
WHEN     m.MAND_COMPTE_CREDIT IS NULL
	AND NVL (m.mand_rejet, 0) = 1
THEN
   TRUNC (M.MAND_DT_RJT)
WHEN M.MAND_DATE_TRAIT IS NULL
THEN
   TRUNC (M.MAND_DATE_RECUP)
WHEN NVL (m.mand_date_recup,
		 TO_DATE ('01/01/2019', 'DD/MM/RRRR')) =
	TO_DATE ('01/01/2019', 'DD/MM/RRRR')
THEN
   TRUNC (M.MAND_DATE_ORD)
END                DATE_SITUATION,
M.ASSIGNATAIRE,
M.MANDATAIRE,
'' OVPCPAYEUR
FROM EXECUTION%ANNEE%.MANDAT@dblcca2          M,
TITRE_XXI           T,
EXECUTION%ANNEE%.ECRITURE@dblcca2        E,
T_TRANSFERT  TR
WHERE 1=1
AND M.COMPTE NOT IN ('6011','6131','6522','6521')
AND M.MAND_MODE_PAIE = 'OO'
--AND M.SOA = '00-17-0-620-00000'
AND M.ECRI_NUM = E.ECRI_NUM(+)
AND M.ID_MAND = T.ID_MAND(+)
AND T.MAND_NUM_INFO = TR.DET_BEXECUTION%ANNEE%.MANDAT(+)
--           ) group by SUBSTR(SOA,4,2) ;