SELECT  COUNT(m.ECRI_NUM) as NOMBRE,to_char(ECRI_DT_VALID, 'MM') as MOIS
from EXECUTION%ANNEE%.ECRITURE@dblcca2 t,EXECUTION%ANNEE%.MANDAT@dblcca2 m WHERE t.ECRI_NUM(+) = m.ECRI_NUM
%WHERE%
AND MAND_VISA_VALIDE = 1 
GROUP BY to_char(ECRI_DT_VALID, 'MM')
ORDER BY to_char(ECRI_DT_VALID, 'MM') ASC