SELECT * FROM (	
	
	select ROW_NUMBER() OVER (ORDER BY M.MAND_NUM_INFO ASC) AS r__,
	COUNT(*) OVER () AS found_rows,t.*,m.soa,m.compte,m.commune,m.ID_MAND,REJET_NOTE,MAND_DT_RJT,
	(SELECT PSTP_LIBELLE FROM EXECUTION%ANNEE%.POSTE_COMPTABLE_ORIGINAL pc WHERE M.ASSIGNATAIRE=pc.PSTP_CODE) as ASSIGNATAIRE,
	(SELECT PSTP_LIBELLE FROM EXECUTION%ANNEE%.POSTE_COMPTABLE_ORIGINAL pc WHERE M.MANDATAIRE=pc.PSTP_CODE) as MANDATAIRE,
	m.MAND_VISA_TEF,
	m.MAND_NUM_INFO,  
	m.MAND_OBJET,
	m.MAND_DATE_RECUP,
	m.MAND_DATE_REEL_VISA,
	CASE
	WHEN m.MAND_MODE_PAIE = 'VB' THEN 'Virement bancaire'
	WHEN m.MAND_MODE_PAIE = 'OO' THEN 'Opération d`ordre'
	WHEN m.MAND_MODE_PAIE = 'BC' THEN 'Bon de Caisse'
	WHEN m.MAND_MODE_PAIE = 'OP' THEN 'Ordre de paiement'
	END MAND_MODE_PAIE,
	CONCAT (TO_CHAR(MAND_MONTANT,'FM999G999G999G999D00' , 'NLS_NUMERIC_CHARACTERS = '', '' '), ' Ar') AS MAND_MONTANT1

	from EXECUTION%ANNEE%.ECRITURE t,EXECUTION%ANNEE%.MANDAT m WHERE t.ECRI_NUM(+) = m.ECRI_NUM

	%WHERE%
) niv1

WHERE r__ BETWEEN %DEBUT% AND %FIN%