
select * from (
SELECT  M.ASSIGNATAIRE,
       MIN_CODE,
	   T.CODE_TIERS,
	   (SELECT PSTP_LIBELLE FROM EXECUTION2023.POSTE_COMPTABLE_ORIGINAL pc WHERE M.ASSIGNATAIRE=pc.PSTP_CODE) as ASSIGNATAIRE1,
	   (SELECT PSTP_LIBELLE FROM EXECUTION2023.POSTE_COMPTABLE_ORIGINAL pc WHERE M.MANDATAIRE=pc.PSTP_CODE) as MANDATAIRE1,
       MIN_ABREV,
       MIN_LIBELLE,
       INTITULE,
       M.EXERCICE,
       M.ACTIVITE,
       M.INDICATEUR        PROGRAMME,
       M.SOA,
       M.COMMUNE           MISSION,
       M.COMPTE,
       M.MAND_COMPTE_CREDIT,
       MAND_CPTAUX_DEBIT,
       M.MAND_NUM_INFO     MANDAT,
	   M.MAND_OBJET,
	   m.MAND_DATE_RECUP,
	   T.TITULAIRE,
	   M.MAND_DATE_REEL_VISA,
       MAND_UTR_VISA       USER_VALID_LCAD,
       MAND_UTR_RECUP,
       CODE_UTILISATEUR    TYPE_MAND,
       MAND_NUMERO_BMAND,
       MAND_DATE_ORD,
       MAND_CODE_TIERS,
       MAND_ORDONNATEUR,
       MAND_NUMERO_BE,
       MAND_MODE_PAIE,
       MAND_MONTANT,
	   CONCAT (TO_CHAR(MAND_MONTANT,'FM999G999G999G999D00' , 'NLS_NUMERIC_CHARACTERS = '', '' '), ' Ar') AS MAND_MONTANT1,
       MAND_LIBELLE,
       TYPE_ENG,
       REJET_NOTE,
       ECRI_DT_CECRITURE,
       ECRI_DT_SECRITURE,
       MAND_DATE_VISA,
       MAND_DATE_TRAIT,
       E.ECRI_REF,
       PERI_CODE,
       CASE
           WHEN NVL (MAND_REJET, 0) = 1
           THEN
               'REJET'
           WHEN NVL (ECRI_VALID, 0) = 1
           THEN
               'ADMIS EN DEPENSE'
           WHEN NVL (MAND_VISA_VALIDE, 0) = 1 AND NVL (ECRI_VALID, 0) = 0
           THEN
               'EN INSTANCE DE VISA COMPTA'
           ELSE
               'INSTANCE DE PRISE EN CHARGE'
       END                 STATUT,
       V.NOTEREF,
       NOTEMT,
       NOTEDATEEDIT,
       NOTEDATEVALID,
       DMDVIRREF,
       DMDVIRMT,
       DMDVIRDATEEDIT,
       DMDVIRDATEVALID,
       OVEXO,
       OVREF,
       OVPCPAYEUR,
       OVDATEEDIT,
       DATEEXECUTIONOV,
       V.CATEG_DEPENSE,
       v.STATUS            STATUTS_NOTE,
       CASE
           WHEN NVL (ECRI_VALID, 0) = 1 AND V.NOTESTATUS NOT IN (4, 5)
           THEN
               'INSTANCE DE PAIEMENT'
           WHEN NVL (ECRI_VALID, 0) = 1 AND V.NOTESTATUS IN (4, 5)
           THEN
               'PAYE'
           ELSE
               'NON VISE COMPTA'
       END                 STATUT_PAIEMENT
  FROM EXECUTION2023.MANDAT M, EXECUTION2023.ECRITURE E, CATIA.V_VIREMENT V, EXECUTION2023.TITRE_XXI T
 WHERE     M.ECRI_NUM = E.ECRI_NUM(+)
       AND M.ENTITE = E.ENTITE(+)
       AND M.MAND_NUM_INFO = V.MANDAT(+)
       AND M.EXERCICE = v.exercice(+)
	   AND M.ID_MAND = T.ID_MAND(+)
       AND M.MAND_MODE_PAIE IN ('VB', 'ME')
) 
--AND M.EXERCICE = '2023'   
--AND M.MIN_ABREV = 'MEF'   
--AND SUBSTR (M.soa, 1, 2) IN ('90','06','40','20') 
-- ORDER BY E.ECRI_NUM   asc   
OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY

