SELECT COUNT(*) over () found_rows,trcf.* from (
WITH TRANSFERT AS (
SELECT 
    
   SUBSTR(LECR_REFERENCE_OPER,-12,12) MANDAT, B.*, TY.BT_TYPE_STATUS_LIB
FROM EXECUTION%ANNEE%.LGECRITURE L
, TRANSFERT.DETAILS_BT_EMIS DT, TRANSFERT.BT B
, TRANSFERT.BT_TYPE_STATUS TY
--,TRANSFERT.DET_BT_REC COUV
WHERE
/*ECRI_NUM = 128601
AND*/ LECR_REFERENCE_OPER LIKE 'CD|MD-%'
AND LECR_SENS  = 'C'
AND  L.LECR_NUM = DT.DET_BT_ENV_LECRNUM 
AND L.ENTITE = DT.BTE_ENVOYEUR
AND B.BT_ID = DT.DET_BT_ENV_ID
AND B.BT_STATUS = TY.BT_TYPE_STATUS_ID
--AND B.BT_ID = COUV.DET_BT_ENV_ID
)
SELECT M.ASSIGNATAIRE,
       MIN_CODE,
       MIN_ABREV,
       MIN_LIBELLE,
       INTITULE,
       M.EXERCICE,
       M.ACTIVITE,
       M.INDICATEUR         PROGRAMME,
       M.SOA,
       M.COMMUNE            MISSION,
       M.COMPTE,
       M.MAND_COMPTE_CREDIT,
       MAND_CPTAUX_DEBIT,
       M.MAND_NUM_INFO      MANDAT,
       MAND_UTR_VISA        USER_VALID_LCAD,
       MAND_UTR_RECUP,
       CODE_UTILISATEUR     TYPE_MAND,
       MAND_NUMERO_BMAND,
       MAND_DATE_ORD,
       MAND_CODE_TIERS,
       MAND_ORDONNATEUR,
       MAND_NUMERO_BE,
       MAND_MODE_PAIE,
       MAND_MONTANT,
       MAND_LIBELLE,
       TYPE_ENG,
       REJET_NOTE,
       MAND_DATE_RECUP,
       ECRI_DT_CECRITURE,
       ECRI_DT_SECRITURE,
       MAND_DATE_VISA,
       MAND_DATE_TRAIT,
       E.ECRI_REF,
       PERI_CODE,
       NVL(BT_TYPE_STATUS_LIB,CASE WHEN NVL(MAND_REJET,0) = 1 THEN 'REJET'
            WHEN NVL(ECRI_VALID,0) = 1 THEN 'ADMIS EN DEPENSE'
            WHEN NVL(MAND_VISA_VALIDE,0) = 1 AND NVL(ECRI_VALID,0) = 0 THEN 'EN INSTANCE DE VISA COMPTA'
            ELSE 'INSTANCE DE PRISE EN CHARGE' END) STATUS,T.*,E.*
FROM EXECUTION%ANNEE%.MANDAT M, EXECUTION%ANNEE%.ECRITURE E, TRANSFERT T
 WHERE  M.MAND_MODE_PAIE = 'OO'
 AND M.ECRI_NUM = E.ECRI_NUM(+) AND M.ENTITE = E.ENTITE(+)
 AND M.MAND_NUM_INFO = T.MANDAT (+)

 ) trcf
%WHERE%