SELECT COUNT(*) over () found_rows, M.ASSIGNATAIRE,
       MIN_CODE,
	   M.MAND_NUM_INFO,
	   M.ECRI_NUM ECRINUM,
	   (SELECT PSTP_LIBELLE FROM EXECUTION%ANNEE%.POSTE_COMPTABLE_ORIGINAL pc WHERE M.ASSIGNATAIRE=pc.PSTP_CODE) as ASSIGNATAIRE1,
	   (SELECT PSTP_LIBELLE FROM EXECUTION%ANNEE%.POSTE_COMPTABLE_ORIGINAL pc WHERE M.MANDATAIRE=pc.PSTP_CODE) as MANDATAIRE1,
       MIN_ABREV,
       MIN_LIBELLE,
	   CASE
					WHEN m.MAND_MODE_PAIE = 'VB' THEN 'Virement bancaire'
					WHEN m.MAND_MODE_PAIE = 'OO' THEN 'Opération d`ordre'
					WHEN m.MAND_MODE_PAIE = 'BC' THEN 'Bon de Caisse'
					WHEN m.MAND_MODE_PAIE = 'OP' THEN 'Ordre de paiement'
	   END MAND_MODE_PAIE1,
       INTITULE,
       M.EXERCICE,
       M.ACTIVITE,
       M.INDICATEUR         PROGRAMME,
       M.SOA,
       M.COMMUNE            MISSION,
       M.COMPTE,
       M.MAND_COMPTE_CREDIT,
       MAND_CPTAUX_DEBIT,
       M.MAND_NUM_INFO      MANDAT1,
       MAND_UTR_VISA        USER_VALID_LCAD,
       MAND_UTR_RECUP,
       CODE_UTILISATEUR     TYPE_MAND,
       MAND_NUMERO_BMAND,
       MAND_DATE_ORD,
       MAND_CODE_TIERS,
       MAND_ORDONNATEUR,
       MAND_NUMERO_BE,
       MAND_MODE_PAIE,
       MAND_MONTANT,
	   CONCAT (TO_CHAR(MAND_MONTANT,'FM999G999G999G999D00' , 'NLS_NUMERIC_CHARACTERS = '', '' '), ' Ar') AS MAND_MONTANT1,
       MAND_LIBELLE,
       TYPE_ENG,
       REJET_NOTE,
       MAND_DATE_RECUP,
       MAND_DATE_VISA,
       MAND_DATE_TRAIT,
       NVL(BT_TYPE_STATUS_LIB,CASE WHEN NVL(MAND_REJET,0) = 1 THEN 'REJET'
            WHEN NVL(ECRI_VALID,0) = 1 THEN 'ADMIS EN DEPENSE'
            WHEN NVL(MAND_VISA_VALIDE,0) = 1 AND NVL(ECRI_VALID,0) = 0 THEN 'EN INSTANCE DE VISA COMPTA'
            ELSE 'INSTANCE DE PRISE EN CHARGE' END) STATUS,T.*,E.*
FROM EXECUTION%ANNEE%.MANDAT M, EXECUTION%ANNEE%.ECRITURE E, V_TRANSFERT T
 WHERE  M.MAND_MODE_PAIE = 'OO'
 AND M.ECRI_NUM = E.ECRI_NUM(+) AND M.ENTITE = E.ENTITE(+)
 AND M.MAND_NUM_INFO = T.MANDAT (+)
 %WHERE%